version: '3'
services:
  web:
        build:
                context: .
                dockerfile: Dockerfile
        image: cnpmjs.org:2.19.4
        ports:
                - "7001:7001"
                - "7002:7002"
        volumes:
               - ./cnpm-volume-data/config/config.js:/var/app/cnpmjs.org/config/config.js
               - ./cnpm-volume-data/data/:/var/www
               - ./cnpm-volume-data/docs/web:/var/app/cnpmjs.org/docs/web

  mysql-db:
    image: mysql:5.6
    restart: always
    environment :
      MYSQL_ROOT_PASSWORD: no-password
      MYSQL_DATABASE: cnpmjs_test
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./cnpm-volume-data/cnpm-init.sql:/docker-entrypoint-initdb.d/cnpm-init.sql           

